name: Release

on:
  release:
    types: [created, edited]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.20.0'

    - name: Package
      run: |
        make package -o dispatcher/dispatcher.pb.go -o dispatcher/dispatcher_grpc.pb.go CERTS_DIR=/etc/vinyl/certs
        tar cvvjf vinit-x86_64.tar.bz2 vinit-x86_64

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          vinit-x86_64.tar.bz2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
